package rules
import com.binod.DroolsComplexRule.Store;
import com.binod.DroolsComplexRule.Resutado;
import java.util.ArrayList;
import java.util.HashMap;

rule "Offer for Paytm"
salience 3

	when
		 $result: Resutado()
		 $store: Store($state: state)
		 $tests: ArrayList()
		 from accumulate( store : Store(  $state == state ),
		    init( ArrayList<Store> tests = new ArrayList<Store>(); ),
		    action(
		        tests.add(store);
		    ),
		    reverse(
		       	tests.remove(store);
		    ),
		    result( tests )
		 )
	then
		$result.getResultado().put($state, $tests);
		//System.out.println("Encontrado mais de duas linhas de movimentação do caixa" + $tests);
	end
